package dev.uktcteam.hackathon.entities.coordinates;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "coordinates")
public class Coordinate {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "coordinate_id", nullable = false,updatable = false)
    private Long coordinateId;

    @Column(name = "x")
    private int x;

    @Column(name = "y")
    private int y;

    public Long getId() {
        return coordinateId;
    }

    // Constructors, getters, setters - generated by Lombok
}